# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipelock < Formula
  desc "Security harness for AI agents"
  homepage "https://github.com/luckyPipewrench/pipelock"
  version "0.1.4"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/luckyPipewrench/pipelock/releases/download/v0.1.4/pipelock_0.1.4_darwin_amd64.tar.gz"
      sha256 "fbbdf22de508a9830848dc1a35b7331e6060e80c00ffcca50b88bd2feba74630"
    end
    on_arm do
      url "https://github.com/luckyPipewrench/pipelock/releases/download/v0.1.4/pipelock_0.1.4_darwin_arm64.tar.gz"
      sha256 "db3ecd6b35ce7a027a02446b422d08472f738b6d70baac090a113a3b8e61dfaa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/luckyPipewrench/pipelock/releases/download/v0.1.4/pipelock_0.1.4_linux_amd64.tar.gz"
      sha256 "c1e5f5b814e4069c065007798d8635fb49c9f6f8d2bf38eea86a55725bba1962"
    end
    on_arm do
      url "https://github.com/luckyPipewrench/pipelock/releases/download/v0.1.4/pipelock_0.1.4_linux_arm64.tar.gz"
      sha256 "e0a22839a41dcf37d547065fd3168fe6eb8e6240213ac6df341d51f04fa72480"
    end
  end

  def install
    bin.install "pipelock"
  end

  test do
    system "#{bin}/pipelock", "version"
  end
end
