# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipelock < Formula
  desc "Security firewall for AI agents"
  homepage "https://github.com/luckyPipewrench/pipelock"
  version "2.1.0"
  license "Apache-2.0 AND Elastic-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/luckyPipewrench/pipelock/releases/download/v2.1.0/pipelock_2.1.0_darwin_amd64.tar.gz"
      sha256 "4a639926ddbd5ca9d7e5517d2d8de2264760efa541a04c9071d9221940290d21"

      define_method(:install) do
        bin.install "pipelock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/luckyPipewrench/pipelock/releases/download/v2.1.0/pipelock_2.1.0_darwin_arm64.tar.gz"
      sha256 "dc139b20ec64b701c5caff5b0f93e638149cdb7288be44d0b5b8f3c18efad903"

      define_method(:install) do
        bin.install "pipelock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/luckyPipewrench/pipelock/releases/download/v2.1.0/pipelock_2.1.0_linux_amd64.tar.gz"
      sha256 "87baa4f906efa5c18bb60b447aba61e4634649e0d769904771623ab6b360ad74"
      define_method(:install) do
        bin.install "pipelock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/luckyPipewrench/pipelock/releases/download/v2.1.0/pipelock_2.1.0_linux_arm64.tar.gz"
      sha256 "4051fd4853bfb698cf8c1f09f8fd899d2a43835f62e7526568f5f8d58a4cdc0e"
      define_method(:install) do
        bin.install "pipelock"
      end
    end
  end

  test do
    system "#{bin}/pipelock", "version"
  end
end
